Document: darcs-to-git
Title: Debian darcs-to-git Manual
Author: <insert document author here>
Abstract: This manual describes what darcs-to-git is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/darcs-to-git/darcs-to-git.sgml.gz

Format: postscript
Files: /usr/share/doc/darcs-to-git/darcs-to-git.ps.gz

Format: text
Files: /usr/share/doc/darcs-to-git/darcs-to-git.text.gz

Format: HTML
Index: /usr/share/doc/darcs-to-git/html/index.html
Files: /usr/share/doc/darcs-to-git/html/*.html

  
